##    自定义属性
#my:
#  value: "主配置"
#  number: ${random.int}
#  uuid: ${random.int}
#server:
#  port: 8888
##动态执行配置文件
#spring:
#  profiles:
#    active: dev
##  number: ${random.int}
##  uuid: ${random.int}
#tomcat配置
server:
  context-path: /
  port: 8086
  tomcat:
    uri-encoding: utf-8

#   LOGGING
logging:
  level:
    ROOT: warn
  file: dev.log

#自定义属性
my:
  value: "dev配置"
  number: ${random.int}
  uuid: ${random.uuid}


spring:
  #mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb?characterEncoding=utf8&useSSL=true
    username: root
    password: '033096'
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource

    tomcat:   #    连接池
      initial-size: 4
#  liveReload
  devtools:
    livereload:
      enabled: false
      port: 54321 #解决LiveReload Server 打不开的问题  可能因为端口被占用的问题
#  JMS
  mail:
    host: smtp.qq.com
    port: 465
    username: 1040993883@qq.com
    password: AI062295xuan
    protocol: smtp
    default-encoding: UTF-8

#thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false



